import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="dark" lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}


// import "./globals.css"; // Import global CSS from the same directory
// import { Inter } from "next/font/google"; // Import Google Font
// import { ReactNode } from "react"; // Import ReactNode for typing

// const inter = Inter({ subsets: ["latin"], display: "optional" });

// export default function RootLayout({ children }: { children: ReactNode }) {
//   return (
//     <html lang="en">
//       <head>
//         <link
//           rel="stylesheet"
//           href="https://fonts.googleapis.com/icon?family=Material+Symbols+Outlined"
//         />
//       </head>
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
